// Runtime deployment config for THE CLOSE ROOM (Module 4 capstone).
// Plain script (not a module) so facilitators can swap values per event without
// touching application code.
//
// This is a standalone instance that shares an origin with the Module 2 lab
// (the Variance Vault), so it uses its own localStorage keys ('controlRoom.*',
// historical names wired into js/state.js and js/leaderboard.js). Do not point
// both instances at the same keys, or a Variance Vault run in progress will
// bleed into this one.
window.CONTROL_ROOM_CONFIG = {
  // Where the game fetches station content from (generated by tools/generate-hashes.mjs).
  roomsUrl: 'config/rooms.json',

  // Shared leaderboard backend (Supabase).
  //
  // Running LOCAL-ONLY for this cohort (both blank by design). Sign-off codes
  // still validate client-side and the game is fully playable; the leaderboard
  // is final-submission-only and per-device, and admin.html sees only teams
  // that played in this browser. The UI states this. To switch on a shared
  // board, create the table with the DDL in README.md and fill these in.
  // The anon key is publishable by design — protect the table with RLS.
  supabaseUrl: '',        // e.g. 'https://abcd1234.supabase.co'
  supabaseAnonKey: '',
  supabaseTable: 'control_room_teams',

  // Optional gate for admin.html: if set, the page requires ?key=<adminKey>.
  // A deterrent for curious participants, not real security.
  adminKey: ''
};
